<?php defined('SYSPATH') or die('No direct script access.');
class Welcome_Controller extends Site_Controller {

	// Disable this controller when Kohana is set to production mode.
	// See http://docs.kohanaphp.com/installation/deployment for more details.
	//const ALLOW_PRODUCTION = FALSE;

	// Set the name of the template to use
	public $template = 'template';

	public function index()
	{
		if($this->subdomain != 'digibutter')
		{
			if($this->isMobile)
				$view = new View('homes/'.$this->subdomain.'_m');
			else
				$view = new View('homes/'.$this->subdomain);
		}
		else
			$view = new View('home');

		// In Kohana, all views are loaded and treated as objects.
		$this->template->content = $view;

		// You can assign anything variable to a view by using standard OOP
		// methods. In my welcome view, the $title variable will be assigned
		// the value I give it here.
		$this->template->title = 'pickupsticks';
	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller